### ISSUE TITLE
Add support for localized HTML

### ISSUE THREAD

**Issue by mdouchin** [3liz/lizmap-pgmetadata-module#6]
The upcoming version of the plugin will allow to use a new parameter to set the locale. See the PR https://github.com/3liz/qgis-pgmetadata-plugin/pull/50

In Lizmap module, we should

* get the current locale from `jLocale`
* test if this locale corresponds to one of the available locales. At present, `$available_locales = array('en', 'fr');`
* use the new version of the function `SELECT pgmetadata.get_dataset_item_html_content('{schema}', '{table}', '{locale}');` with a try / catch (and use the old one if the first failed `SELECT pgmetadata.get_dataset_item_html_content('{schema}', '{table}');`

cc @drillinP @Gustry

**Comment by pdrillin** [comment]
Commits: a2405cbc4773da6369eebbf8bebc883fbc7cb52a, d643f921be7e78773c320eab991fbcd48c6d5e1b, 6984ecf44e4af6debc84d23ee56faf1bea001e53
